### ISSUE TITLE
Extension Load Error on Start

### ISSUE THREAD

**Issue by frankcash** [diracdeltas/signal-muon#14]
Hello,

I am running on Ubuntu 16.04 with Node 7.7.2.

I followed the installation steps, and run `npm start` and receive the following output:

```
> signal-muon@0.0.1 start /home/foobar/Code/signal-muon
> node ./tools/start.js --debug=5859 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

extension load error 
```

**Comment by frankcash** [comment]
I failed to clone recursively, my bad.

**Comment by diracdeltas** [comment]
Gotcha. 0f0a23025380698ad965cdcb770efa12ab200af2 should make the 'extension load error' message more useful.
