### ISSUE TITLE
Messaging myself

### ISSUE THREAD

**Issue by stalane** [diracdeltas/signal-muon#15]
v1.4.31
Linux Chrome Version 56.0.2924.87 (64-bit)
Android 7.0

So I sent myself some messages (which is weird) and the replies dont show up in the Desktop App but do in Android 7.0

![s3](https://cloud.githubusercontent.com/assets/4401195/23779824/b94f67ec-057d-11e7-9da9-279b6a34a3af.jpg)

![s4](https://cloud.githubusercontent.com/assets/4401195/23779830/c133ebf4-057d-11e7-949c-24805c8a020e.png)

**Comment by diracdeltas** [comment]
Are you running via `npm start` or the package?

**Comment by stalane** [comment]
I just cloned the repo and ....

![s5](https://cloud.githubusercontent.com/assets/4401195/23779934/7cd22a24-057e-11e7-9edf-623cea362954.png)

**Comment by diracdeltas** [comment]
@stalane do you mean that you downloaded the linux package at https://github.com/diracdeltas/signal-muon/releases?

**Comment by diracdeltas** [comment]
nvm, i can repro this in OS X. not sure if it is an issue with Muon or just a Signal-Desktop issue.

**Comment by stalane** [comment]
Yes. I downloaded the package.

**Comment by AndHell** [comment]
this also happens in the regular Signal-Desktop version. 
https://github.com/WhisperSystems/Signal-Desktop/pull/959

**Comment by diracdeltas** [comment]
Closing since it is an issue in regular Signal Desktop
