### ISSUE TITLE
Can't create window after closing it on Mac

### ISSUE THREAD

**Issue by mammuth** [diracdeltas/signal-muon#25]
When all windows are closed, on mac the app still stays running (as added intentionally). However, a window should be able to be recreated, when clicking on the icon of the running app. That's the common macOS behavior.

Reproduce:
- Open Signal Muon
- Close it by eg. clicking on the red close-button 
- Click on the icon in the dock of the still running app

Expected: A new window spawns
Actual: Nothing happens

**Comment by diracdeltas** [comment]
There is sample code for doing this in https://github.com/brave/muon-quick/blob/master/main.js#L41-L56

**Comment by diracdeltas** [comment]
fixed by #42
