### ISSUE TITLE
Focus message box when the app gets focus

### ISSUE THREAD

**Issue by mammuth** [diracdeltas/signal-muon#27]
Do:
- Have Signal in foreground
- Open another app so Signal is in background
- Focus Signal again

Expected: The message box of the first conversation should be focused so the user can immediately type
Actual:  Message box is not focused

**Comment by asafonov** [comment]
@diracdeltas It looks like onfocus for document.body of the Signal-Desktop subproject works only after a click on the window.

If I try to catch BrowserWindow.on('focused' ) it works great but I do not know for now how to send this event to browser window.

If you have time could you please point me to the right direction? Thank you a lot

**Comment by diracdeltas** [comment]
@asafonov probably the webview element has to be in focus. you can call `webview.focus` in index.js when BrowserWindow is focused. 

if you need to send a message between the main process (main.js) and a renderer main process (index.js), you can use `BrowserWindow.getFocusedWindow().webContents.send`

**Comment by asafonov** [comment]
@diracdeltas Thank you. I'll have a look at this issue

**Comment by diracdeltas** [comment]
this was broken by https://github.com/diracdeltas/signal-muon/commit/a7da1d2e686d57cbc7fffa0ea31de2b5dd8558f3 since 'require' no longer works in the window context

**Comment by asafonov** [comment]
@diracdeltas Thank you for letting know. Anyway, I cannot reproduce the issue with the latest changes. If it's working for you too, I can cleanup the code

**Comment by diracdeltas** [comment]
hmm maybe i misunderstood the original issue. in the latest master, if i focus the input box, then switch to another app, then switch back to Signal, the input box is still focused. however, if the input box is not originally focused, it does not become focused when Signal is focused. is that expected?

**Comment by asafonov** [comment]
@diracdeltas This is exact behavior of the chrome app version, so it looks good for me
Before this updtae input did not become focused even if it was focused originally, so I believe the fixing code can be simply removed

**Comment by diracdeltas** [comment]
@asafonov thank you for clarifying!
