### ISSUE TITLE
fresh install: app opens with no windows

### ISSUE THREAD

**Issue by glyph** [diracdeltas/signal-muon#31]
- cloned the repo
- `npm install`
- `npm run build`
- `open Signal-darwin-x64/Signal.app`

App opens, but… nothing. The `Signal` menu just has "About Application" and "Quit".

For reference this is 58765f3967091ca3cb13f431e1121e1e9f7a49e5.  `sw_vers`:

```
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
```

Please let me know if there's any more useful diagnostic info I can provide.

**Comment by asafonov** [comment]
@glyph 
I don't have a Mac OS to check now but didn't you forget to do `git submodule update --init --recursive`?

**Comment by glyph** [comment]
@asafonov Indeed, I didn't do that. `README.md` did not say I needed to :). Next time I'm in front of the machine in question I'll give it a shot…

**Comment by diracdeltas** [comment]
packaged builds may have been broken due to #28 but i think it is fixed now. there is a separate bug where Signal is taking a long time to start up and initialize the window.

**Comment by glyph** [comment]
"a long time" meaning how long? I tried this again with submodules properly initialized and it took long enough that it went into "application not responding", burning CPU for a good 3 minutes.

**Comment by diracdeltas** [comment]
see #33
