### ISSUE TITLE
app is taking a long time to start up

### ISSUE THREAD

**Issue by diracdeltas** [diracdeltas/signal-muon#33]
This started happening sometime over the weekend. I see either a blank window or no windows for about a minute.

**Comment by diracdeltas** [comment]
seems due to the `storage.onready` event taking a long time to fire

**Comment by diracdeltas** [comment]
I restarted and now the problem is gone. :/

**Comment by glyph** [comment]
Same thing happened here, actually.  It kept happening until I rebooted - and Signal-muon wasn't the only app that was hanging in a bizarre place.

Hopefully the new OS update will fix whatever this was??? `¯\_(ツ)_/¯`

Thanks for investigating!

**Comment by diracdeltas** [comment]
@glyph good to know. for me, i think it was only Electron/Muon apps that were hanging.

**Comment by diracdeltas** [comment]
cannot repro anymore, may have been fixed by the muon update.

**Comment by glyph** [comment]
Thanks for looking into it!
