### ISSUE TITLE
Clicking new message notification raises an exception on Mac

### ISSUE THREAD

**Issue by garrettr** [diracdeltas/signal-muon#4]
## Steps to Reproduce

1. Someone sends you a message
2. A notification dialog appears in the top right corner of the screen
3. You think "Oh, neat! Someone out there still likes me. Let's see what they have to say..."
4. You click on the notification dialog

### Expected Behavior

The app is focused, and the new message (that triggered the notification) is displayed.

### Observed Behavior

<img width="797" alt="screen shot 2017-03-06 at 1 50 49 am" src="https://cloud.githubusercontent.com/assets/407302/23605409/75c08304-0211-11e7-9e33-1decfb1cce39.png">

**Comment by diracdeltas** [comment]
thank you for the gift^H^H^H^H issue

**Comment by diracdeltas** [comment]
The error is fixed by https://github.com/diracdeltas/signal-muon/commit/9cd88db757593945cd90f33195ba93cfc6c9f22b
