### ISSUE TITLE
Build on windows fails

### ISSUE THREAD

**Issue by rgnuru** [diracdeltas/signal-muon#43]
Building the package only works when commenting out some options in tools\buildPackage.js out:

cmds = cmds.concat([
  'node ./node_modules/electron-packager/cli.js . Signal' +
    ' --overwrite' +
    ' --platform=' + process.platform +
    ' --arch=' + arch +
    ' --version=' + electronVersion +
//    ' --icon=' + appIcon +
    ' --asar=false' 
//    ' --app-version=' + signalVersion +
//    ' --build-version=' + electronVersion
])

also the command "mkdir" doesn't know the flag "-p" on windows:
// cmds.push('mkdir -p ' + extensionsPath)

**Comment by diracdeltas** [comment]
adding the 'help wanted' label because i don't run Windows. it should be an easy fix (change the cmds conditionally depending on `isWindows`)

**Comment by epsilontheta** [comment]
That is due to a bug in brave/electron-packager (not renaming brave.exe leads to a subsequent fault https://github.com/brave/electron-packager/commit/50bd4db906f9b6ed0a11617891c5e81517e60695#diff-382da7e2b6e191171138bbcfc8c3a94c)

**Comment by diracdeltas** [comment]
closed by #53

**Comment by sergeevabc** [comment]
There is no Windows binary planned, right? :(
