### ISSUE TITLE
Make it difficult to attack

### ISSUE THREAD

**Issue by 3n-mb** [diracdeltas/signal-muon#45]
When main window is created in [main.js](https://github.com/diracdeltas/signal-muon/blob/master/main.js#L57) it better have `webPreferences.nodeIntegration = false` or better `webPreferences.sandbox = true` in eletron's terms.
Without this, we are not using electron/muon's gift for secure software, which is a possibility to keep sensitive stuff in core/main, and all UI in renderer processes, isolated from each other as much as possible.
Call it security in depth. Others call it [lazy security](https://www.youtube.com/watch?v=eL5o4PFuxTY).

I realize, you are working with existing code, porting from electron to muon. Thus, as part of reshuffling, you have a chance to make it better.

When you split all crypto, sessions, whatnot into main process, and have UI in sandbox-ed renderer, then it would be possible to try out UI skins written by others. Like a cat-themed UI :) , for example. Removing the worry about UI effort messing up critical parts. The [lazy thing](https://www.youtube.com/watch?v=eL5o4PFuxTY) is a proper reference here at minute 52.

**Comment by diracdeltas** [comment]
@3n-mb muon already has nodeIntegration false and sandbox true by default. it does not support nodeIntegration or disabling the sandbox.

**Comment by 3n-mb** [comment]
Sounds cool!

**Comment by 3n-mb** [comment]
@diracdeltas , actually, I am reading muon's docs, and, for example [this passage](https://github.com/brave/muon/blob/master/docs/tutorial/security.md#ignoring-above-advice) sounds like one must pro-actively disable node integration. Is this stale doc on a part of muon?

**Comment by 3n-mb** [comment]
@diracdeltas [here](https://github.com/brave/muon/blob/master/docs/api/browser-window.md#new-browserwindowoptions) docs say:

> nodeIntegration Boolean - Whether node integration is enabled. Default is true.

Is it a stale doc? Or, should you try `nodeIntegration = false` to see if anything changes. It seems that signal code is an extension thingy, i.e. that architecture will not notice the flag anyway.

**Comment by 3n-mb** [comment]
I asked for clarification [on muon](https://github.com/brave/muon/issues/178) about docs. If muon has strong defaults, it should be properly displayed!

**Comment by diracdeltas** [comment]
agree, muon's documentation is not up-to-date. it is not really ready for use by external projects yet unless you are a member of Brave or in touch with the Brave team. (which i am part of)
