### ISSUE TITLE
Click on the "Attach" button does nothing

### ISSUE THREAD

**Issue by asafonov** [diracdeltas/signal-muon#7]
When I click "Attach" button, nothing happens, only one string in console:
```
"[15939:0307/165918:INFO:CONSOLE(49)] "index.html: ", source: chrome-extension://iopnjipkpnmbpjaalcjcpcbfcnjknmmo/js/debugLog.js (49)"
```

**Comment by diracdeltas** [comment]
`chrome.fileSystem` is probably not fully supported. you may be able to just replace it with an HTML5 file dialog opener (https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications).
